import java.util.HashMap;
import java.util.Map;

public class Contacts {

  public static Map<String, String> contacts = new HashMap<>();

  static {
    contacts.put("Manan Bharara", "manan.bharara@gmail.com");
//    contacts.put("Manan Bharara (TW)", "mananbh@thoughtworks.com");

    contacts.put("Anand P Mishra","apmishraa@gmail.com");
    contacts.put("Digvijay Pundir","pundir.digvijay@gmail.com");
    contacts.put("Barkha Arora","barkhaarora88@gmail.com");
    contacts.put("Ajaz Ahmad","ajaz.ahmad2006@outlook.com");
    contacts.put("Nidhi Sharma","nidhi31sh@gmail.com");
    contacts.put("Sumit Bansal","sumitbansal684@gmail.com");
    contacts.put("Nitish Choudhary","choudhary.nitish@gmail.com");
    contacts.put("Navin Chopra","navin_chopra1986@hotmail.com");
    contacts.put("Rohit Ranjan","ranjan.meta.iitkgp@gmail.com");
    contacts.put("Ajay Pratap Singh","ajeya1z1@gmail.com");
    contacts.put("Rajnish singh","rajnishsingh7592@gmail.com");
    contacts.put("Gaganpreet Singh","willey.singh@gmail.com");
    contacts.put("Ankit Sharma","ankits.ku@gmail.com");
    contacts.put("FAZAL AHMED GANI","fazalgani0@gmail.com");
    contacts.put("yogesh bhatt","yogesh_774@yahoo.co.in");
    contacts.put("Lalit Goyal","lalitgoyal88@gmail.com");
    contacts.put("Ravinder Singh Gandhi","iravinder.gandhi@gmail.com");
    contacts.put("Tithi Narang","tithinarang@gmail.com");
    contacts.put("pritika","pritikaa.arora@gmail.com");
    contacts.put("Deepak kumar gupta","dpkgupta68@gmail.com");
    contacts.put("Divya Jain","divyajain711@gmail.com");
    contacts.put("Vikas Srivastava","sriva.vikas@gmail.com");
    contacts.put("Ravi Prakash","raviprakash1857@gmail.com");
    contacts.put("Deepak","deepak.bammi86@gmail.com");
    contacts.put("Rohit Dhyani","rohit.dhyanikotdwara@gmail.com");
    contacts.put("Praveen kumar","pbhati440@gmail.com");
    contacts.put("Nandan upadhyay","rock.nandan@yahoo.in");
    contacts.put("rakesh kumar","kushwaha.rakesh86@gmail.com");
    contacts.put("Anil Kumar","anilrock9407@gmail.com");
    contacts.put("Pooja Gupta","poojagupta.may91@gmail.com");
    contacts.put("Sagar Wadhwa","sagarwadhwa16@gmail.com");
    contacts.put("Tej Pratap Pandey","ptejpratap.111@gmail.com");
    contacts.put("Priya Gautam","priyagtm199@gmail.com");
    contacts.put("Akhil P Bhagat","bhagat3000@gmail.com");
    contacts.put("Baijnath Gupta","baijnathgupta7@gmail.com");
    contacts.put("SAHIL SALUJA","salujasahil29@gmail.com");
    contacts.put("Gautam sharma","bb_gautam@hotmail.com");
    contacts.put("Paramjeet Singh","param_cool00@yahoo.com");
    contacts.put("Nehu Gumber","gumbernehu@gmail.com");
    contacts.put("BHAGYA SHRI","bhagyashri406@gmail.com");
    contacts.put("Robin sharma","Robii_87@rediffmail.com");
    contacts.put("sandeep kumar tyagi","sandytyagi2013@gmail.com");
    contacts.put("Kaushal kumar","developer.kaushal@gmail.com");
    contacts.put("Shri Ram Sahu","ram.sahu22@gmail.com");
    contacts.put("Shashvat Nayan Verma","mrshashvatverma@gmail.com");
    contacts.put("Vinit Ranjan Srivastva","dear.vinit.sr@gmail.com");
    contacts.put("Akriti Goel","akritigoel25@gmail.com");
    contacts.put("Anoop Kumar Soni","anoopsoni.28@gmail.com");
    contacts.put("Marked Confidential","Marked Confidential");
    contacts.put("Gaurav Kamra","grv_kamra@yahoo.com");
    contacts.put("Atul Prakash Singh","atul.prakash07@gmail.com");
    contacts.put("Pragati Singh","er.pragatisingh@gmail.com");
    contacts.put("Sudama Sharma","sudama.sharma@gmail.com");
    contacts.put("MOHIT SRIVASTAVA","mohit.sree@gmail.com");
    contacts.put("pawan kumar","pawan_75kumar@yahoo.com");
    contacts.put("Vinod Kumar","nbkumarvi5@gmail.com");
    contacts.put("Pawan Kumar Mishra","pwnballia@gmail.com");
    contacts.put("Narendra Kumar Singh","nkssps@gmail.com");
    contacts.put("Pankaj Chawla","pankaj.chawla621@gmail.com");
    contacts.put("Gyanendra Sharma","sharmagyanu2010@gmail.com");
    contacts.put("Aditi Sharma","aditisharma1403@gmail.com");
    contacts.put("Sanjeev Kumar","sanju925018@gmail.com");
    contacts.put("gagandeep singh","gaganraymous24@gmail.com");
    contacts.put("ZAFAR ALI","zafaralidel@gmail.com");
    contacts.put("Pawan Vashisht","networks.pawan@gmail.com");
    contacts.put("Akhil Kumar Punia","akhil.punia@gmail.com");
    contacts.put("SANDEEP KUMAR","ssandy93@gmail.com");
    contacts.put("Deepu Shivhare","shivhare.deepu81@gmail.com");
    contacts.put("Dibyajyoti Das","dibyajyoti.das2@gmail.com");
    contacts.put("MAYUR GUPTA","mayur_gupta@live.in");
    contacts.put("Muthu Kumarun","ms.muthukumarun@gmail.com");
    contacts.put("Priyanka saini","priyanka.saini50@gmail.com");
    contacts.put("ANKIT MADAN","ankit.career05@gmail.com");
    contacts.put("Rajesh Kumar","rajeshrao352@gmail.com");
    contacts.put("Rahul Kumar","rhl.kushwaha1992@gmail.com");
    contacts.put("Anchal Sharma","replyanchal@gmail.com");
    contacts.put("Nirankar Nath","nathn704@gmail.com");
    contacts.put("AMARJIT KUMAR","amarjitkumar43@gmail.com");
    contacts.put("mithilesh kumar pandey","mithileshpandey48@gmail.com");
    contacts.put("Vikrant Prajapati","vikrantprajapati83@gmail.com");
    contacts.put("SANCHITA SRIVASTAVA","sanchita.srivastava13@gmail.com");
    contacts.put("Om Parkash Rana","omprakashrana87@gmail.com");
    contacts.put("Mithilesh kumar pandey","mithileshpandey1000@gmail.com");
    contacts.put("Mithileshpandey","mithileshpandey1000@gmail.com");
    contacts.put("Sharad Gupta","sharadgupta1124@gmail.commob");
    contacts.put("KUNAL GIRDHAR","girdharkunal91@gmail.com");
    contacts.put("vikas juyal","greatboy_vikas@yahoo.com");
    contacts.put("Sunny Sharma","sharmasunny02@gmail.com");
    contacts.put("Mohammad Iqubal","ansariinjnu@gmail.com");
    contacts.put("servpreet singh","servpreet.singh@gmail.com");
    contacts.put("Deepak Srivastava","deepaksrivastava101257@gmail.com");
    contacts.put("Saumya Agrawal","saumyaagrawal12@micamail.in");
    contacts.put("GAURAV ANAND","GAURAV07SONU@gmail.com");
    contacts.put("Chandan Kumar","chandansharma86@live.com");
    contacts.put("Ravneet Singh","toravneetsingh@gmail.com");
    contacts.put("Muskan","muskaankumawat11@gmail.com");
    contacts.put("Himanshu Verma","cse.1005610047@gmail.com");
    contacts.put("Meenakshi Chaudhary","minaxichaudhary.571@gmail.com");
    contacts.put("Priyansu Das","priyansu@gmail.com");
    contacts.put("Tinku Kumar","tinku3366@gmail.com");
    contacts.put("Hritik Kumar","kumar.hritik9999@gmail.com");
    contacts.put("Mukhtar Yadav","mukhtar_yadav@rediffmail.com");
    contacts.put("s.sreenath reddy","srinathsirigiri@gmail.com");
    contacts.put("NIKHIL VERMA","n.nikhilverma89@gmail.com");
    contacts.put("Mohammad saleem","saleem.amu126@gmail.com");
    contacts.put("Ranjt Kumar","ranjit1975.p@gmail.com");
    contacts.put("Rahul Sareen","sareenr58@yahoo.com");
    contacts.put("Shruti Sharma","shruti.sharmaten@gmail.com");
    contacts.put("Md Haroon","emailmdharoon@gmail.com");
    contacts.put("Vishal Choudhary","vishalchoudhary10495@gmail.com");
    contacts.put("Utkarsh Kumar","utkarshkumar0100@Gmail.com");
    contacts.put("POONAM","POONAM7JUNE@rediffmail.com");
    contacts.put("poonam","poonam7june@gmail.com");
    contacts.put("Anil kaumar","anilgautam9350@gmail.com");
    contacts.put("Sikandar Khan","unosikandar@gmail.com");
    contacts.put("Zeeshan Ahmed","zeeshan019@gmail.com");
    contacts.put("Vishwas Rao","vishurao@gmail.com");
    contacts.put("Inder Kumar","rathore619@gmail.com");
    contacts.put("Saransh Kumar","saranshkumar54@gmail.com");
    contacts.put("Ashish Kumar Singh","improbableashish@gmail.com");
    contacts.put("sulabh sharma","sulabh.et@gmail.com");
    contacts.put("Tabish Nasar","infotabish@gmail.com");
    contacts.put("uttam kumar pandey","upndey@gmail.com");
    contacts.put("Deep Narayan Singh","deepnarayan118@gmail.com");
    contacts.put("FAIZAN","faizanhusain9811@gmail.com");
    contacts.put("Rajesh Yadav","raj48yadav@gmail.com");
    contacts.put("Keshav Jha","keshav91.jha@gmail.com");
    contacts.put("Aryak Anmol Mudgil","aryak.mudgil93@gmail.com");
    contacts.put("Amit Kumar Srivastava","amit.srivastava.isc@gmail.com");
    contacts.put("satyam kumar","sk214313@gmail.com");
    contacts.put("Deepak kashyap","dk383874@gmail.com");
    contacts.put("Twinkle","twinklevarmani5@gmail.com");
    contacts.put("Yash Kohli","itsmeyash@icloud.com");
    contacts.put("santosh kumar","santosh_banzan@yahoo.co.in");
    contacts.put("Anshul Meghani","anshul.meghani@outlook.com");
    contacts.put("Savita Agrawal","mail2savita@gmail.com");
    contacts.put("GAURAV DIXIT","gauravmurcha@gmail.com");
    contacts.put("utkarsh gupta","animatorutkarsh@gmail.com");
    contacts.put("Avinash Ojha","balajee1702@gmail.com");
    contacts.put("PARUL GUPTA","parul6422@yahoo.com");
    contacts.put("Priya Gupta","pari9122@gmail.com");
    contacts.put("Sanjeet Tiwari","ssanjeettiwari@gmail.com");
    contacts.put("V","softwareengineer11@gmail.com");
    contacts.put("Sonali Sinha","futureisback@gmail.com");
    contacts.put("Rajat Khattar","rajatkhattar2012@gmail.com");
    contacts.put("Vikrant Sood","joy1000in@gmail.com");
    contacts.put("Gaurav Kumar Singh","gksingh.mail@gmail.com");
    contacts.put("Bibekananda sarangi","bibek346@gmail.com");
    contacts.put("Gopal Upadhyay","gopal.upadhyay12@gmail.com");
    contacts.put("Shubhra Singh","sinha.shubhra@gmail.com");
    contacts.put("Arti Aggarwal","arti_agg@yahoo.com");
    contacts.put("Firoz Khan","fkckhan@gmail.com");
    contacts.put("Mohd. Aseem Khan","aseemkhan007@gmail.com");
    contacts.put("Chhavi Rai","chhavi16in@gmail.com");
    contacts.put("Dheeraj Kumar Gupta","mediamaster.in@gmail.com");
    contacts.put("Amit Jain","amitjain.coer191@gmail.com");
    contacts.put("Vishwas Kumar","er.vishvas.kumar@gmail.com");
    contacts.put("Deepak Malik","deepakvce84@gmail.com");
    contacts.put("Disha Vig","dishavig@gmail.com");
    contacts.put("Arjya Nanda","nanda.arjya@gmail.com");
    contacts.put("Vinod Kumar","vinodtech.kumar@gmail.com");
    contacts.put("Alok Ranjan","ranjan.alok@gmail.com");
    contacts.put("Saurabh Bajaj","bajajsaur@gmail.com");
    contacts.put("Sujeet Singh","sachan.sujeet@gmail.com");
    contacts.put("Arun","choudhary.arun08@gmail.com");
    contacts.put("Hitesh Ghai","hitesh.ghai@hotmail.com");
    contacts.put("Nidhi Gautam","nidhi4gautam@gmail.com");
    contacts.put("Naresh Kumar","mailnaresh111@yahoo.in");
    contacts.put("SITANSHU SHARMA","sitanshu.sharma@hotmail.com");
    contacts.put("Sahil Mahajan","mahajansahil12@gmail.com");
    contacts.put("Suruchi Sharma","suruchi07.sharma@gmail.com");
    contacts.put("Niket Anand","nike2030@gmail.com");
    contacts.put("Deepak Kumar","deepu_verma2009@live.com");
    contacts.put("Arjun Singh","rawat.singh520@GMAIL.COM");
    contacts.put("pradeep kumar","pradeephanuman1989@gmail.com");
    contacts.put("Vijay Soni","vs4vijay@gmail.com");
    contacts.put("Kumar Shorav","k.shorav@gmail.com");
    contacts.put("Buddhi Ram Sharma","buddh.md@GMAIL.COM");
    contacts.put("Nishant nayan","nayan_webexpert@yahoo.co.in");
    contacts.put("Prateek Sharma","prateekksharma1989@gmail.com");
    contacts.put("devendra Kumar Verma","devensoni.devendra@gmail.com");
    contacts.put("Bal Krishna Mishra","balkrishna.mshr@gmail.com");
    contacts.put("Kavita Pokhriyal","k.pokhriyal@gmail.com");
    contacts.put("Lalit Sharma","sharma.lalit721@gmail.com");
    contacts.put("Divya","divyag10@gmail.com");
    contacts.put("Richa Sharma","richieisinn@gmail.com");
    contacts.put("Sonal Agarwal","sonal.testing@gmail.com");
    contacts.put("Suraj Pratap Singh","surajbca2006@gmail.com");
    contacts.put("Prateek Bhatia","prateek.bhatia87@gmail.com");
    contacts.put("Nitish Verma","nitish.verma@rediffmail.com");
    contacts.put("ANKIT CHOPRA","ankitchopra121@gmail.com");
    contacts.put("Piyush Kumar","piyush9568@gmail.com");
    contacts.put("manpreet","manpreetkaurduggal@gmail.com");
    contacts.put("Ravi Kumar","ravikumr7@gmail.com");
    contacts.put("Sourabh","sourabhm89@yahoo.com");
    contacts.put("SHIVANK LAUL","shiv_158@yahoo.com");
    contacts.put("Gobind Singh Bakshi","gobindbakshi89@gmail.com");
    contacts.put("Jagdeep Singh Baniwal","jagdeepbaniwal@gmail.com");
    contacts.put("Saurabh Anand","saurabhanand.jsr@gmail.com");
    contacts.put("Kunal Manchanda","manchanda_kunal@hotmail.com");
    contacts.put("Nikhil Kumar","thakran1387@gmail.com");
    contacts.put("Nakul Kaushik","nakul.kaushik88@gmail.com");
    contacts.put("Mayank Srivastava","mayank061082@gmail.com");
    contacts.put("Kumar Rishabh","kkumarrishabh@gmail.com");
    contacts.put("Shubham Khandelwal","kh.shubham@gmail.com");
    contacts.put("Bhupendra Singh Rautela","Bhupendra.rautela@live.com");
    contacts.put("Rashmi Karan","rashmi.karan0605@gmail.com");
    contacts.put("pushpank kaushik","cs.pushpank@gmail.com");
    contacts.put("Roohi Rajput","rajputroohi@gmail.com");
    contacts.put("Ankit Kapoor","ankitkapoor21@gmail.com");
    contacts.put("Subrat Narayan","subrat_narayan@yahoo.com");
    contacts.put("SHIVANI CHOUDHARY","scsangwan23@gmail.com");
    contacts.put("Pushkar Pandey","pushkar1913.p@gmail.com");
    contacts.put("Rohan Nigam","rohan.ngm@gmail.com");
    contacts.put("Megha Mehta","mmehta.ten@gmail.com");
    contacts.put("SHIPRA SHARMA","rajmeenashipra@gmail.com");
    contacts.put("Davinder Singh","getdavindersingh@gmail.com");
    contacts.put("Neha Aggarwal","mail.neha89@gmail.com");
    contacts.put("Deepak Kumar","deepakbong@gmail.com");
    contacts.put("Satya Prakash Solanki","satya.solanki2010@gmail.com");
    contacts.put("Sudeep Singh","sudeep.singh1004@gmail.com");
    contacts.put("Mayur","mayukathuria007@india.com");
    contacts.put("Parkash Kumar Barick","kumar.prakash841@gmail.com");
    contacts.put("Himanshu Hasija","Hasijahimanshu@outlook.com");
    contacts.put("VARUN JAIN","varunjain344@gmail.com");
    contacts.put("ASHUTOSH SAXENA","ashutoshsaxena06@gmail.com");
    contacts.put("sanya bhardwaj","sanyabhardwaj.11@gmail.com");
    contacts.put("Reema Tiwari","reematiwari2410@gmail.com");
    contacts.put("Shalinee Singh","shalinee.singh1993@gmail.com");
    contacts.put("Chhotu Dilip Bambal","chhotu0602@hotmail.com");
    contacts.put("Aayushi Jain","aayushijain1616@gmail.com");
    contacts.put("Vipul kakkar","vipul.kakkar9@gmail.com");
    contacts.put("Nishant Batheja","nishantbatheja77@gmail.com");
    contacts.put("Ankit Kumar Gupta","ankit.gupta124@gmail.com");
    contacts.put("Har simran minhas","minhashoney26@gmail.com");
    contacts.put("Somendra Singh Chauhan","somendrachauhan89@gmail.com");
    contacts.put("Deepak Solanki","dpaksolanki99@gmail.com");
    contacts.put("Parasnath Chhabilal","parasvarma@hotmail.com");
    contacts.put("Zeeshan Ahmad Khan","khan.zeeshanahmad@gmail.com");
    contacts.put("Kriti Thareja","kritithareja6@gmail.com");
    contacts.put("Vaishali Singh","vaishali.technology@gmail.com");
    contacts.put("sujeet","sujeet.ait@gmail.com");
    contacts.put("Dhaneshwar Kumar","dhcciever4@gmail.com");
    contacts.put("Varun Bhardwaj","varunb719@gmail.com");
    contacts.put("Sahil Dheer","sahildheer1990@gmail.com");
    contacts.put("Hemant Kumar","uxd.hemant@gmail.com");
    contacts.put("Himanshu Goel","himanshugoel19@gmail.com");
    contacts.put("Prakash Mishra","prakashmishra.orange@gmail.com");
    contacts.put("Anurag Karki","anutotti@gmail.com");
    contacts.put("Kaveri singh","kaverisingh89@gmail.com");
    contacts.put("Dheeraj Shandilya","dheeraj.silicon@gmail.com");
    contacts.put("nishant kumar","nishantengineer343@gmail.com");
    contacts.put("Pankaj Kumar","dev.pankaj@outlook.com");
    contacts.put("saurabh patyal","saurabh89.patyal@gmail.com");
    contacts.put("Anshika Mittal","mittalanshika406@gmail.com");
    contacts.put("Krishnanand Sadanandan","krishnanand_ps@yahoo.com");
    contacts.put("Sharad Awasthi","sharad.awasthi.win@gmail.com");
    contacts.put("Shweta Kaushik","shweta_sharma1982@hotmail.com");
    contacts.put("Amit Luthra","amit.lut@gmail.com");
    contacts.put("Divya Tripathi","3.joshi@gmail.com");
    contacts.put("Himanshu Kulshresth","himanshu.kulshresth@yahoo.com");
    contacts.put("Prageet Pathak","prageet.pathak@gmail.com");
    contacts.put("Pintu Kumar","pintu_kum@hotmail.com");
    contacts.put("Yogesh Sharma","yogesh56@gmail.com");
    contacts.put("Rajat Gupta","rajatgupta79@gmail.com");
    contacts.put("Kapil Saxena","batcheet@gmail.com");
    contacts.put("Dilshad Saifi","dilshad1985saifi@gmail.com");
    contacts.put("Vishal Sharma Lead Consultant","vishalqa7@gmail.com");
    contacts.put("Himanshu Garg","heman3003@yahoo.com");
    contacts.put("Gaurav Kumar","ergauravverma@rediffmail.com");
    contacts.put("Meenu","meenu_bhadana25@yahoo.co.in");
    contacts.put("Gaurav Pateriya","gaurav_cs046@yahoo.co.in");
    contacts.put("Ankit Kaushik","ankitkaushikdm@gmail.com");
    contacts.put("nimish jain","nimish01@gmail.com");
    contacts.put("devesh kumar pant","deveshpntt@gmail.com");
    contacts.put("Gaurav Pateriya","gaurav.pateriya@gmail.com");
    contacts.put("Jitender Madaan","jitendermadaan24@gmail.com");
    contacts.put("abhishek Srivastava","abhigsri83@yahoo.co.in");
    contacts.put("Rajeev Singh","raj_21eev@yahoo.co.in");
    contacts.put("deepak","deepakchandna007@gmail.com");
    contacts.put("vishal chaudhary","vitcharles@Gmail.com");
    contacts.put("VAKUL SHARMA","vakul57@gmail.com");
    contacts.put("Sumit Chaudhary","sumchaudhary@aol.com");
    contacts.put("Gaurav yadav","sendtogaurav@outlook.com");
    contacts.put("Maneesh Singh","mksingh202@yahoo.in");
    contacts.put("Pankaj Bhatt","engineer.pankajbhatt@yahoo.com");
    contacts.put("Aavesh","aveshcool@gmail.com");
    contacts.put("Sarika Garg","sarikagarg86@gmail.com");
    contacts.put("Prashant","prashvat@yahoo.in");
    contacts.put("RAHUL GOYAL","goyal.rahul0194@gmail.com");
    contacts.put("surbhi chaturvedi","surchat.14@gmail.com");
    contacts.put("Richa Kala","13novrkala@gmail.com");
    contacts.put("Sumit Saxena","sumit_saxena@ymail.com");
    contacts.put("Smriti Singh","smritirsingh@gmail.com");
    contacts.put("Ruchika","ruchika1801@gmail.com");
    contacts.put("Bhawani Prasad","bhawani.bit@gmail.com");
    contacts.put("Manisha Sarova","manisha.sarova000@gmail.com");
    contacts.put("Nikhil","nikhilsrivastavait06@gmail.com");
    contacts.put("Mangal Chaubey","mangalchaubey@gmail.com");
    contacts.put("ankit","engankit.sharma@gmail.com");
    contacts.put("PRADEEP SHUKLA.","pradeep.shuklabbs@gmail.com");
    contacts.put("satya prakash priyadarshi","satyaprakash.ranchi@gmail.com");
    contacts.put("Ayush Kapoor","ayushkapoor665@gmail.com");
    contacts.put("Mayur","mayur.artist88@gmail.com");
    contacts.put("Prateek Toshniwal","toshniwal.prateek@gmail.com");
    contacts.put("Amit Mudgal","amitm.mudgal@gmail.com");
    contacts.put("Kamal Singh","kamalsinghsoam@gmail.com");
    contacts.put("Swapnil Mehrotra","swapnil139@gmail.com");
    contacts.put("RAHUL MANDOTHIA","rahulmandothia6@gmail.com");
    contacts.put("sunil prasad","tosunil1983@gmail.com");
    contacts.put("Rashmi Sharma","rashmisharma7988@gmail.com");
    contacts.put("Tanuja Shukla","tanuja1217@gmail.com");
    contacts.put("JITENDER BHATIA","jim3j1989@gmail.com");
    contacts.put("SMITA DASH","dash.smita89@gmail.com");
    contacts.put("uma","umabhardwaj98@gmail.com");
    contacts.put("Mahesh Bhakuni","maheshbhakuni.leon@gmail.com");
    contacts.put("Dhruv Kumar","Dhruvkumardce.17@gmail.com");
    contacts.put("Ashutosh Aggarwal","Ashutosh2729@gmail.com");
    contacts.put("Jai Dhiman","jaidhiman61@gmail.com");
    contacts.put("Anshul Chaudhary","meetanshu.2k8@gmail.com");
    contacts.put("Sumit Kumar","sumitarora46@gmail.com");
    contacts.put("Akash Grover","akashgrover91@gmail.com");
    contacts.put("Suman Aswal","suman88aswal@gmail.com");
    contacts.put("Hitesh Bhardwaj","bhardwajhitesh2@gmail.com");
    contacts.put("Akshat Tripathi","akshattripathi01@gmail.com");
    contacts.put("Deepak Goyal","deepakgoyal1807@gmail.com");
    contacts.put("SHREYA KHOSLA","khosla.shreya08@gmail.com");
    contacts.put("Garima Saxena","saxena1026@gmail.com");
    contacts.put("Nidhi Sharma","nidhi501sharma@gmail.com");
    contacts.put("Vishal Katiyar","kativish@gmail.com");
    contacts.put("Priyanka Dabral","priyankadce4130@yahoo.com");
    contacts.put("Naman Dogra","naman.dogra@gmail.com");
    contacts.put("Tarun Arora","tarunmakeaway@gmail.com");
    contacts.put("Manvi Mehta","manvi5956@gmail.com");
    contacts.put("pravasini pal","palalu86@gmail.com");
    contacts.put("Pravin Tiwari","pravin.tiwari1515@gmail.com");
    contacts.put("Shipra Singh","shipra.c.singh@gmail.com");
    contacts.put("Archana Prasad","archana_p02@hotmail.com");
    contacts.put("Surya Pratap Singh","spsingh6536@gmail.com");
    contacts.put("M Hima Sagar Reddy","modemsagar@gmail.com");
    contacts.put("Shivam Gautam","shivamgautam18.10@live.com");
    contacts.put("Parvin Bansal","bansalparvin.1@gmail.com");
    contacts.put("Archit Sharma","sharma13archit@gmail.com");
    contacts.put("Saurabh Kumar","saurabh.mca2014@gmail.com");
    contacts.put("Sankalp Gaur","sankalp.gaur1@gmail.com");
    contacts.put("Ranjana Yadav","sony.ranjana@gmail.com");
    contacts.put("Abhirup Nandi","tech.abhirup21@gmail.com");
    contacts.put("Aakash Kumar","aki.149209@gmail.com");
    contacts.put("Vishesh Sharma","vishesh.sharma11@hotmail.com");
    contacts.put("Shamsher Singh","shamsher.sqa@gmail.com");
    contacts.put("Mayurika Patel","myrkpatel8@gmail.com");
    contacts.put("Chanchal Sharma","sharma.chanchal.06@gmail.com");
    contacts.put("Mohd Yassar Amjad","yassar_sabri@yahoo.co.in");
    contacts.put("uttam kumar","uttam6602@gmail.com");
    contacts.put("Puneet Sharma","puneet.sharma@live.com");
    contacts.put("Sandeep Tikarya","stikarya@gmail.com");
    contacts.put("Pranav Gupta","pranavgup@gmail.com");
    contacts.put("ASHISH KUMAR","aashish.kumr@gmail.com");
    contacts.put("Jitender","jitu1680@gmail.com");
    contacts.put("anika verma","anika.sareen@gmail.com");
    contacts.put("shruti","shruti191986@yahoo.com");
    contacts.put("Shivam Srivastava","shivamsrivastava1618@gmail.com");
    contacts.put("Pooja","pooja.ttr@gmail.com");
    contacts.put("Dewank Kumar","dewank3@gmail.com");
    contacts.put("Inderpreet","indu3931@gmail.com");
    contacts.put("Chetan Kumar","er.gargchetan@gmail.com");
    contacts.put("Yaman Vohra","vohrayaman@yahoo.com");
    contacts.put("Neha Chhabra","nehachh.1987@gmail.com");
    contacts.put("Varun Batra","varun_batra86@yahoo.com");
    contacts.put("Garima Bansal","garimabansal9790@gmail.com");
    contacts.put("Priyanka Sharma","mailpriyankasharma9@gmail.com");
    contacts.put("Aviraj Roy","aviraj.roy@gmail.com");
    contacts.put("Ashutosh Singh","ashutosh0289@gmail.com");
    contacts.put("Amit Kumar","amit88sr@gmail.com");
    contacts.put("Akanksha prasad","akankshaprasad06@gmail.com");
    contacts.put("Pradeep Tiwari","pradeep.tiwari89@hotmail.com");
    contacts.put("Heena Satyarthi","heena.satyarthi02@gmail.com");
    contacts.put("Rashmi Ranjan Mohanty","ranjanrashmi53@gmail.com");
    contacts.put("Rahul gupta","rahulgupta986@gmail.com");
    contacts.put("Shivam Sidharth","shivam.sidharth@gmail.com");
    contacts.put("Amit Soni","soniamit218@gmail.com");
    contacts.put("SHREE MAITY","shreemaity@gmail.com");
    contacts.put("Dharm Vrat","dharmvrat2011@gmail.com");
    contacts.put("Paras Sharma","sparas2803@gmail.com");
    contacts.put("vikrant singh","vikrant2k@gmail.com");
    contacts.put("hemant sharma","hemantsai27@gmail.com");
    contacts.put("Jatinkumar","jatinkumarniit@gmail.com");
    contacts.put("Uttam Singh Rawat","rawat.uttam@gmail.com");
    contacts.put("Pratap Singh Bisht","bishttech23@gmail.com");
    contacts.put("Anjali Vaswani","anjali.vaswani86@yahoo.com");
    contacts.put("Suchitra","adsuchitra@yahoo.com");
    contacts.put("IVIN JACOB","hitsivin@yahoo.com");
    contacts.put("Joyeeta Das","joyeeta_mca.gnit@rediffmail.com");
    contacts.put("Amit Kumar","reach2amitgola@gmail.com");
    contacts.put("Amit Goyal","toamitgoyal@gmail.com");
    contacts.put("Prashant","prashant214@yahoo.com");
    contacts.put("amit kumar","akamitkumar708@gmail.com");
    contacts.put("Kanchan","kkanchan1911@gmail.com");
    contacts.put("Ritesh Joshi","ritesh.bispl23@gmail.com");
    contacts.put("neeraj sardana","nee.srd21@gmail.com");
    contacts.put("RAHUL NEGI","torahulnegi@gmail.com");
    contacts.put("Suraj Bhan Rana","suraj.roadies@gmail.com");
    contacts.put("Sukriti arora","sukritia9@gmail.com");
    contacts.put("Saorabh Kumar","saorabh04@gmail.com");
    contacts.put("Silutina Nayak","silutina2014.nayak@gmail.com");
    contacts.put("Paras Mendiratta","paras.mendiratta@gmail.com");
    contacts.put("rakeshkumar","rk.gbpec@gmail.com");
    contacts.put("Mukesh Bakshi","mailmukeshbakshi@gmail.com");
    contacts.put("SWETA YADAV","swetayadav08@gmail.com");
    contacts.put("Manish Arora","manisharora4u@gmail.com");
    contacts.put("Neelesh Garg","neeleshgarg@gmail.com");
    contacts.put("Sunil Kumar Verma","sunilverma105@gmail.com");
    contacts.put("Navneet Kaur","navi161@gmail.com");
    contacts.put("Purva Agarwal","nicks.agarwal@gmail.com");
    contacts.put("MANOJ KUMUAR","ER.MANOJYADAV24@GMAIL.COM");
    contacts.put("SHEKHAR KUMAR PATRA","shekh.patra@gmail.com");
    contacts.put("Monika Arora","monika.arora89@gmail.com");
    contacts.put("Urvashi Singh","urvashiauyc@gmail.com");
    contacts.put("Saurabh Goel","saurabhcem@gmail.com");
    contacts.put("Tanvi Agarwal","tanviagarwal28@gmail.com");
    contacts.put("NITISH Kumar","rajvitz@yahoo.com");
    contacts.put("Himanshu Mishra","4himanshumishra@gmail.com");
    contacts.put("Rishi Nagpal","rishinagpal@gmail.com");
    contacts.put("Komal Kain","komal2008k@gmail.com");
    contacts.put("Rupa Kumari","rupakt24@gmail.com");
    contacts.put("Divya Shrivastava.","shrivastava.divya12@gmail.com");
    contacts.put("vikas bhardwaj","vikasbhardwajb@gmail.com");
    contacts.put("Anchit Jain","jain.nchit@hotmail.com");
    contacts.put("Vishal Singla","vsingla.qa@gmail.com");
    contacts.put("Nitin Talan","talan.nitin5@gmail.com");
    contacts.put("Shobhit Singhal","singhalshobhit16@gmail.com");
    contacts.put("Rishika Mehta","rishika_02@yahoo.co.in");
    contacts.put("Shashank Tripathi","007shashank786@gmail.com");
    contacts.put("Harshita Kanvaria","h.kanvaria23@gmail.com");
    contacts.put("Alok Trivedi","tri_genius@rediffmail.com");
    contacts.put("Fazeel Ahmad","fazeelahmad@gmail.com");
    contacts.put("Rahul Shrotriya","rahulrahul83@yahoo.co.in");
    contacts.put("MITHUN","mkayal80@gmail.com");
    contacts.put("Sohan Pal Singh Rawat","Sohanpsingh@yahoo.com");
    contacts.put("Vinay Kumar","vinay.vks84@gmail.com");
    contacts.put("Rajesh","sap.rk.tiwari@gmail.com");
    contacts.put("Manoranjan kumar","kumar.ranjan86@gmail.com");
    contacts.put("VIBHU KAUSHIK","kaushik.vibhu@gmail.com");
    contacts.put("SANKET JASWAL","sanketjaswal@yahoo.com");
    contacts.put("Ruchika Singh","ruchika_nayar@yahoo.com");
    contacts.put("Avinash Awasthi","avinash.pu@gmail.com");
    contacts.put("EKTA","ektasharma2003@gmail.com");
    contacts.put("Ranjan Khurana","ranjankhuranasp@gmail.com");
    contacts.put("Saurabh Jain","sourabh.sjain@gmail.com");
    contacts.put("Sudhakar Tripathi","suddhu_s@yahoo.com");
    contacts.put("Sher Chand Kamboj","sherag142@gmail.com");
    contacts.put("Ankur Kumar","ank15188@gmail.com");
    contacts.put("paritosh gaur","paritosh.mac@gmail.com");
    contacts.put("SWARNAYU CHAKRABERTY","swarnayu.chakraberty@gmail.com");
    contacts.put("GAURAV GUPTA","grvgupta.ei@gmail.com");
    contacts.put("SUNEETKUMAR","suneet4sap@gmail.com");
    contacts.put("Mohit Kumar Chauhan","ranamohitchouhan@gmail.com");
    contacts.put("KIRTESH TIWARI","kirtesh7feb@gmail.com");
    contacts.put("NIDHI TEWARI","nidhitewari.tewari@gmail.com");
    contacts.put("Puneet Somnani","puneetsomnani@gmail.com");
    contacts.put("Nishant Prakash","nishant.instrument@gmail.com");
    contacts.put("AJAY","ajay09uniyal@gmail.com");
    contacts.put("Akanksha Yadav","akkiyadav2391@gmail.com");
    contacts.put("Govind Singh Rana","gsripl@gmail.com");
    contacts.put("Samba","samba.orfc@gmail.com");
    contacts.put("Garima Nagpal","gnagpal2016@gmail.com");
    contacts.put("RUCHIKA SINGH","ruchika.nayar@yahoo.com");
    contacts.put("hemant sharma","hemantsharma223@gmail.com");
    contacts.put("rijilks","rijil.ks@gmail.com");
  }
}
